services:

  app:
    image: 'docker-vacunapp:latest'
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    expose:
      - 80
    ports:
      - "8087:80"
    container_name: VacunApp
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - frontend

  api:
    image: 'docker-vacunapi:latest'
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
    container_name: VacunApi
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5435/projetoclientedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped
    networks:
      - backend
      - frontend
  db:
    image: 'postgres'
    expose:
      - 5432
    ports:
      - "5435:5432"
    container_name: VacunApiDB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
volumes:
  postgres-data:


networks:
  backend:
  frontend:
